name: mushroom_dick_sdk
description: A Dart SDK of Moguding APP.
version: 1.0.0
homepage: https://github.com/zbLiuLiu/MushroomDick-SDK

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: ^0.12.2
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
